language: java
sudo: required
jdk:
    - oraclejdk8
  
services:
    - docker
    
# before_install:
    # - docker build -t routing-system .
    # - docker tag routing-system andrewer04/routing-system:latest
    
# deploy:
    # provider: script
    # script: bash docker_push
    # on:
      # branch: master
  
branches:
    only:
    - master